### PR TITLE
[APRComp24] RepairLlama

### PR DESCRIPTION
**Pull request by andre15silva**

### CODE REVIEW

**Comment by andre15silva** [comment]
Hi @rshariffdeen @Marti2203 ,

I have finished integrating this first version.
If everything is okay with you, you can merge this as our submission for this round.

My only comment is that the option `secure_hash` is not implemented (or at least is not recognized by cerberus), so I was not able to check that the shasum is correctly verified.

**Comment by Marti2203** [comment]
Hi @andre15silva ,
`secure_hash` is not a command line argument but a flag which we set through the config files. There is an example config file provided in the `config` directory and you can run cerberus with it using `cerberus -c config/config.json` to check it.

**Comment by andre15silva** [comment]
Ah, okay.

I get the following error, but it seems like it is happening while building vulnloc?




Command ran:
`./bin/cerberus --task repair --bug-index 1 --benchmark=aprcompfuncjava --tool=repairllama --use-gpu -c config/config.json`

**Comment by Marti2203** [comment]
Unfortunately, Cerberus currently does not support passing arguments both from the command line and the config file, so the config file takes priority.  I have to check out the vulnloc issue separately, but I suggest to either only use the config file or modify the `secure_hash` variable in `app/core/values.py` and use the command line arguments

**Comment by andre15silva** [comment]
Ack. I hardcoded the value and it seems to work.

Feel free to merge! Thanks :)

**Comment by Marti2203** [comment]
No problem! Will test it on my side and merge :)

**Pull request merged**
